name: Caller Workflow

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  call_pr_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Call Codium PR Agent Workflow
        uses: cryptlex/temp-repo/.github/workflows/pr_agent.yml@main
