name: Reuse PR Agent Workflow

on:
  workflow_call:

jobs:
  call-pr-agent-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Include Workflow from Temp Repo
        uses: cryptlex/temp-repo/.github/workflows/pr_agent.yml@main
